{% set version = "20170708" %}

package:
  name: tmalign
  version: {{ version }}

source:
  url: http://zhanglab.ccmb.med.umich.edu/TM-align/TMtools{{ version }}.tar.gz
  md5: 28da44a874be2ca8d6c6c81ba26e5632

requirements:
  build:
    - {{ compiler('fortran') }} [unix]
    - m2w64-gcc-fortran [win]
    # https://github.com/ContinuumIO/anaconda-issues/issues/8812
    - libgcc-ng         [linux]
    # ld: file not found: crtfastmath.o
    - gcc 4.8           [osx]
  host:
    # Compiler runtime library in build prefix not found in host prefix
    - gcc 4.8           [osx]

build:
  number: 2

test:
  commands:
    - TMalign
    - TMscore

about:
  summary: 'TM-align sequence-order independent protein structure alignment'
  home: https://zhanglab.ccmb.med.umich.edu/TM-align/
  license: BSD-like
